name: Run LinkedIn Job Scraper

on:
  schedule:
    - cron: '0 1,5,9 * * 1-5'  # Runs at 08:00, 12:00, and 16:00 UTC (Monday-Friday)
  workflow_dispatch:  # Allows manual execution from GitHub Actions UI

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
      SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run the LinkedIn Job Scraper
        run: npm run job 
